### ISSUE TITLE
content_style not applied

### ISSUE THREAD

**Issue by mr3k** [tinymce/tinymce-angular#101]
Hi,

I have read the documentation on for example [content_style](https://www.tiny.cloud/docs/configure/content-appearance/#content_style) but still does not get the styling applied. See my example below where I do not want the status bar to be visible.

```
<editor 
formControlName="formControlName" 
[initialValue]="initialValue"
[init]="{ base_url: '/tinymce', height: 300, content_style: '.tox-statusbar {display: none !important;}' }"
></editor>
```

I think also this could be good to highlight in the readme how to apply custom styling as I think this is a basic requirement.

**Comment by SimonFc** [comment]
Hi! The `content_style` property is for CSS that is to be injected into the iframe so that will only affect the look of the content inside the iframe(think styling of the headings you can create etc.). If you wish to override any of the UI CSS you can simply add it to your page holding the tinymce-angular component as you would do with any CSS since the UI isn't contained in the iframe.

To hide the status bar there's actually a ready-made property to achieve this, try setting `statusbar: false` in your init config.

We won't document overrides like the one you have since that would be fragile. There is an official way to change the look of your editor though, read about it [here](https://www.tiny.cloud/docs/advanced/creating-a-skin/#makingoreditingaskin)
