### ISSUE TITLE
Scrolling issues when cursor over editor in material tabs

### ISSUE THREAD

**Issue by dottodot** [tinymce/tinymce-angular#104]
Not sure if this is an issue with tinymce-angular or just tinymce in general but I have a form setup inside a angular material tab and that tab is scrollable using perfect scrollbar similar to this page but obviously with a form rather that text http://angular-material.fusetheme.com/ui/page-layouts/carded/full-width-tabbed-2

If I try and scroll whilst the cursor is over the editor component I can't scroll but if I place my cursor out of the editor component it scrolls fine.

**Comment by dottodot** [comment]
There are also other issue in material tabs. For example clicking on the second tabs and returning to the first loads the editor but without the value and you can't click inside the editor to make any changes.

**Comment by dottodot** [comment]
this seem to seem the tabs issue but not scrolling https://stackblitz.com/edit/angular-9uvqzk?file=src%2Fapp%2Fapp.component.ts

**Comment by SimonFc** [comment]
@dottodot The issue with the tabs is something that has appeared from time to time. It is limited to iframe-mode so if you were to use TinyMCE in inline-mode it should work alright. In addition to the stackblitz you found, I made a Storybook example a little while to illustrate a possible workaround for usage with tabs. Hope this helps! https://github.com/tinymce/tinymce-angular/tree/master/stories/materialtabs

As for the issue with scrolling, I think I would have to see a working example of the setup you have. Sounds like come confusion with which element does the scrolling?

**Comment by dottodot** [comment]
@SimonFc OK I've added a private repo and added you. I can't make it public as it's a paid for theme. 

The location when I've added the editor is src/app/main/ui/page-layouts/carded/full-width-tabbed-2

and the page where you can view the issue is http://localhost:4200/ui/page-layouts/carded/full-width-tabbed-2

**Comment by SimonFc** [comment]
Ah okay, I think I understand what you mean now. It's due to the usage of an iframe(again) in Tiny which captures the scroll. The same thing would happen if you were to just setup a normal iframe and try to scroll when the cursor is hovering it. I can't think of anything on top of my head for how to solve this but I found this [thread](https://stackoverflow.com/questions/27084876/stop-iframe-from-preventing-scrolling-of-parent-document) which might serve a starting point for you.

I'll close this as this is a general iframe issue and not due to tinymce nor tinymce-angular
