### ISSUE TITLE
The first load is successful, and the error is reported again after removal

### ISSUE THREAD

**Issue by zjxcv7** [tinymce/tinymce-angular#116]
1.First load
<img width="1302" alt="截屏2019-11-0717 10 56" src="https://user-images.githubusercontent.com/24834874/68375466-ddb11380-0181-11ea-8946-bc864bdf63ec.png">
2.Load again after deletion
<img width="1302" alt="截屏2019-11-0717 11 37" src="https://user-images.githubusercontent.com/24834874/68375532-f9b4b500-0181-11ea-9450-47431faaac11.png">

I used the modal of  **ng-zorro-antd**
Angular Version:8.2.13

This is the error recurrence link

https://stackblitz.com/edit/ng-zorro-antd-start-d6yfxh

**Comment by SimonFc** [comment]
This is due to TinyMCE using an iframe and Angular not tearing down tinymce-angular when the dialog is closed, it just detaches the component from the dom. Whenever this happens the iframe will re-render and break TinyMCE(native iframe behavior).

A work-around is to do something similar do what we to in this [example](https://github.com/tinymce/tinymce-angular/blob/master/stories/materialtabs/MaterialTabs.component.ts) with Angular Material Tabs. That is, using the ngIf directive to force tinymce-angular to actually tear down on tab change. In your case you would do the same but when your dialog closes.

Hope this helps!

**Comment by zjxcv7** [comment]
Thank you for your help🙏
