### ISSUE TITLE
hosted tinymce angular webpack module loader prefered

### ISSUE THREAD

**Issue by nphias** [tinymce/tinymce-angular#119]
Angular 8.20
webpack 4.39.1
@tinymce/tinymce-angular 3.3.1
tinymce 5.0.16

this stems from trying to work with webpack angular and tinymce
a thread was started here:
https://github.com/tinymce/tinymce/issues/3396
and told to come here :)

first of all adding the tinymce.min.js as global script available in the window object is not popular with the webpack people... who want things done into nicely scoped modules.

to get it working i added this to my webpack.config.js:

`plugins: [
        new HtmlWebpackPlugin(indexConfig),
        new Webpack.ContextReplacementPlugin(/angular([\\\/])core([\\\/])/, path.resolve(__dirname, './src')),
        new CopyWebpackPlugin([
        { from: "./node_modules/tinymce/skins", to: "assets/tinymce/skins" },
        { from: "./node_modules/tinymce/themes", to: "assets/tinymce/themes" },
        { from: "./node_modules/tinymce/plugins", to: "assets/tinymce/plugins" },
        { from: "./node_modules/tinymce/tinymce.min.js", to: "assets/tinymce" }]),
    ],`
and in my index page:

<!DOCTYPE html>
<html>

	<head>
		<meta charset="UTF-8">
		<base href="./">
		<script src="./assets/tinymce/tinymce.min.js"></script>
		<title>Angular Webpack</title>
        <link rel="stylesheet" href="global.scss">
    </head>

	<body>
		<demo-app>Loading ...</demo-app>
	</body>

</html>

my component:

`<editor [(ngModel)]="content" 
                    [init]="{
                            base_url:'assets/tinymce',
                            suffix: '.min',
                            skin_url: 'assets/tinymce/skins/ui/oxide-dark',
                            menubar:false,
etc....`

I would like to know if others are doing it this way and if there is any alternative such as a module enclosed version in the pipeline?

**Comment by SimonFc** [comment]
What you have done is very similar to providing the main tinymce script to the scripts property in the angular.json as described [here](https://github.com/tinymce/tinymce-angular#loading-tinymce-by-yourself). This would make webpack(under the hood) include the tinymce script in the bundle instead of loading it separately in the index page as you have done, but it's still loaded on initial page load though. (And worth mentioning is that tinymce is always made a global in the context its loaded in, no matter how you load the main script)

What you could do if you don't want to load the main tinymce script on initial page load is to add it to a lazy loaded Angular module. I'll just refer you to the official [Angular docs](https://angular.io/guide/lazy-loading-ngmodules) for the details on how to do this. All steps with loading skins/plugins and so on would be the same as if you had included tinymce in your main module.

Hope this helps!
