### ISSUE TITLE
Random unit tests throwing 'Cannot read property 'open' of undefined'

### ISSUE THREAD

**Issue by Excelzn** [tinymce/tinymce-angular#122]
I am randomly getting 'Cannot read property 'open' of undefined' when running my tests. Using the default Jasmine+Karma for Angular. The error in Karma affects random unit tests, even for components that don't use the editor at all. The only reason I know it is TinyMCE is because of the error I get in the console. If I remove the editor from the template that uses it, the error goes away entirely. It also only seems to affect the unit tests as it works fine on the page at runtime.

I did see another closed issue for this error, but that appeared to be a problem with Angular Material's tabs and I am just embedding the editor directly into a form so I don't think the solution applies, as the ng-template tag would never be displayed anywhere.

**Comment by SimonFc** [comment]
You don't happen to be using JSDom for headless testing or something similar?
And when you say that you're getting the error for components that aren't using tinymce-angular, I'm guessing that you mean that you're conditionally not displaying it tinymce-angular in those components? And if so, how do you do that? Would be great if you could provide some code sample of how you use tinymce-angular!

**Comment by Excelzn** [comment]
No we are running the tests in Karma in Chrome.
As for components that don't use tinymce-angular, I am actually talking about components that don't use it at all. We only use the editor on 2 pages, so I made a wrapper component that has our tinymce config in it and that component is the only one that directly uses tinymce-angular. However, I have gotten the error listed as part of the main app component, a placeholder component that only has a router-outlet in it, a component that is just a table, and many others. As far as I can tell, the component that gets flagged as the one with the error is completely random. And even worse, sometimes all the tests work perfectly and the error doesn't show up at all.

I have attached the wrapper component files below so you can see them. I also attached some of the components that I have seen the error appear on, as well as one of the components that DOES use the editor so you can get a better idea how the component is intended to be used.

[product-form.zip](https://github.com/tinymce/tinymce-angular/files/3917738/product-form.zip)
[text-editor.zip](https://github.com/tinymce/tinymce-angular/files/3917730/text-editor.zip)
[placeholder.zip](https://github.com/tinymce/tinymce-angular/files/3917733/placeholder.zip)

**Comment by SimonFc** [comment]
I think I know what the issue is. TinyMCE is being initialized async so your test for "text-editor.component" will finish before TinyMCE has been fully initialized. Then at a later point in time, at a random second test, that setup will fail. If I'm correct this is maybe something we could improve, .i.e. make sure that TinyMCE actually aborts the setup when the tinymce-angular wrapper gets removed.

But to see if this actually is the issue, I've modified your text-editor component + test to use a "onSetup" event (see the latest commit)
[random_unit_tests.zip](https://github.com/tinymce/tinymce-angular/files/3919289/random_unit_tests.zip)
It's similar to how we do it for tinymce-angular itself: https://github.com/tinymce/tinymce-angular/blob/master/tinymce-angular-component/src/test/ts/browser/NgModelTest.ts#L47

**Comment by Excelzn** [comment]
@SimonFc This appears to have solved the problem. I appreciate the help. If the problem returns, I will let you know but I just ran the whole test suite 10 times and didn't get it once, so I believe it is resolved.

Thanks again!
