### ISSUE TITLE
editor doesn't display sometime and display in another  

### ISSUE THREAD

**Issue by hussambawwab** [tinymce/tinymce-angular#123]
when the user open it they can't see the editor component and there is no reason for that because some users see the editor component and they are the most of users and i can't replicate what happen .

**Comment by SimonFc** [comment]
So you're unable to reproduce it on [codesandbox.io](https://codesandbox.io/s/6zlmmkkk1n?fontsize=14)? If so, is there perhaps some other way for you to show or describe when this issue occur? (The more info, the better) Thanks!

**Comment by airasyaqub** [comment]
I think because on hitting the component which is using TinyMCE module, it makes API call to plugins.js and loads all the plugins. The editor will stay hidden until all the plugins will get load. This is whats happening to me. Trying to figure out the solution. I have included TinyMCE within the application.

**Comment by jscasca** [comment]
Hi @hussambawwab @airasyaqub 

Wondering if you have been able to narrow down the issue or replicate the problem consistently?

Any additional info to move forward with this would help otherwise I will close the ticket for inactivity.

**Comment by airasyaqub** [comment]
The problem was same as I mentioned earlier. On initial rendering of tinymce in ur app it loads all required plugins. It stays hidden during that time. I use a loader and generated event  to let user know that some required assets are loading. 'onInit' is the event riggers after all assets are loaded. Below is the code
`<div [hidden]="editorLoaded === false">
													<editor (onInit)="handleEvent($event)" formControlName="inputEditor"
														[init]="defaultConfig">
													</editor>
													<mat-error *ngIf="emailForm.controls.inputEditor.invalid">
														Please enter email body without any script tag.
													</mat-error>
												</div>
												<ng-container *ngIf="editorLoaded === false">
													
												</ng-container>`

In ts file
`	public defaultConfig: any = {
		height: 700,
		base_url: '/tinymce', // Root for resources
		suffix: '.min',
		plugins: [
			'advlist autolink link image lists charmap print hr anchor pagebreak',
			'searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking',
			'table emoticons template paste help'
		],
		browser_spellcheck: true,
		toolbar: 'undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify |' +
			' bullist numlist outdent indent | link image | print media fullpage | ' +
			'forecolor backcolor emoticons | help',
		menubar: 'file edit view insert format tools table help',
		branding: false
	};

	public handleEvent(e) {
		this.editorLoaded = true;
	}
`

**Comment by jscasca** [comment]
Hi @airasyaqub 

It seems very straight forward, I tried replicating your issue but the editor still loads after the div has been hidden before setting `editorLoaded` to `true`. [Sample](https://codesandbox.io/s/tinymceangular-neu58?file=/src/app/app.component.ts)

Could this be caused by another element in the page? Could you create a small replication case to better understand the issue?

**Comment by airasyaqub** [comment]
I think the issue was with @hussambawwab that some users can see the editor component and others not. According to my theory the reason was that sometimes tinymce is being loaded with all necessary assets which makes it stay hidden. Others who can see it is because they have already instantiated the editor somewhere else in the app. Once instantiated tinymce will not load assets again hence user will see it in UI all time. 
 I just stated the reason and a trick to let user know that something is being loaded with skeleton loaders instead of showing nothing at all.
