### ISSUE TITLE
window not defined when served through Angular Univeral

### ISSUE THREAD

**Issue by sukhminderx** [tinymce/tinymce-angular#125]
**What is the current behavior?**

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/6zlmmkkk1n?fontsize=14) or similar.**

**What is the expected behavior?**
I have used ngToolkit for ading angular universal to the app.
I am using the intymce-angular version 3.3.1.
I see that there was some SSR related code added to tinymce-angular a year back.
When I build the code for SSR, the build is successful.
But during the serve command, I get an error in window object which is created by tinymce.
When I removed tinymce, it worked.

**Which versions of TinyMCE/TinyMCE-Angular, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or TinyMCE-Angular?**
3.3.1 is the version

Code snippets:
The assets like themes and other js are added to assets folder:
![image](https://user-images.githubusercontent.com/35064031/71447165-6e9f7680-2751-11ea-80dc-5dc4b97372a0.png)

In angular.json, these files are referenced:
![image](https://user-images.githubusercontent.com/35064031/71447180-91ca2600-2751-11ea-9ab3-1025ffdee9cf.png)

In module:

import { EditorModule } from '@tinymce/tinymce-angular';

@NgModule({
  imports: [
    CommonModule,
    ReactiveFormsModule,
    EditorModule,
    BlogsRoutingModule,

In component:
![image](https://user-images.githubusercontent.com/35064031/71447200-c0480100-2751-11ea-80e0-c07bc340e1b3.png)

![image](https://user-images.githubusercontent.com/35064031/71447210-d48bfe00-2751-11ea-92a1-60b01bae0f3d.png)

**Comment by SimonFc** [comment]
The SSR related thing added to tinymce-angular a year ago was a guard against setting up TinyMCE server side since rendering TinyMCE server side isn't supported (there's a lot of usage of browser-only global objects in TinyMCE). I _think_ what's going on is that the core of TinyMCE(tinymce.js) gets executed during the server side rendering due to your `import 'tinymce';` statement. You're already including tinymce.js as a script to be loaded by having added it to your scripts property in your angular.json file so no need to include it twice anyway.

Try removing that and let me know if this solves the issue! If it does it would be great if you could share some of the code you have.

---

A tips regarding your setup:
```
"assets": [
  { "glob": "**/*", "input": "node_modules/tinymce/skins", "output": "/tinymce/skins/" },
  { "glob": "**/*", "input": "node_modules/tinymce/themes", "output": "/tinymce/themes/" },
  { "glob": "**/*", "input": "node_modules/tinymce/plugins", "output": "/tinymce/plugins/" }
]
```
Use the assets property in your angular.json to make angular copy everything to your assets folder on build. By doing this you no longer need to include the theme.js in your scripts property as this will be lazy-loaded by TinyMCE on init. Also, the content.css you added to your styles property *must* be loaded by TinyMCE since this will be injected into TinyMCE's iframe so removing what you have there and going for the "assets" approach will fix that.

**Comment by sukhminderx** [comment]
The aboce worked.. closing this. Thanks
