### ISSUE TITLE
2-in-1 laptop with Angular deployment issue

### ISSUE THREAD

**Issue by vincer2d2** [tinymce/tinymce-angular#144]
When using a 2-in-1 laptop (multiple models tested):

     - Disable the on-board keyboard/trackpad (remove it from a Microsoft Surface device or flip the keyboard around on hinged devices)
     - Connect an external mouse (bluetooth for example - multiple models tested)
     - When in this state, the buttons and menus within TinyMCE are not clickable, but do still respond to touch. 

It appears to be when the "default" input devices are disabled and the PC is acting as a tablet, the control only responds to touch and not mouse clicks. Interestingly, it does now work on your demo editor on the website (https://www.tiny.cloud/). But our local installation shows this behavior. Using Angular and just today updated to the latest version of the Angular wrapper

**Comment by lnewson** [comment]
@vincer2d2 what version of TinyMCE are you using? As this is unlikely to be an issue with the wrapper itself and more so with TinyMCE. There was an issue that sounds the same in TinyMCE 5.1.0, which we fixed in TinyMCE 5.1.5.

As such I'd double-check what version you are using and make sure it's 5.1.5 or later.

**Comment by vincer2d2** [comment]
I had my developer ensure all was up to date and re-deployed. Seems to be working now. Thanks!
