### ISSUE TITLE
Including tinymce.min.js in .angular-cli.json doesn't work

### ISSUE THREAD

**Issue by aaron-wti** [tinymce/tinymce-angular#2]
Originally in my index.html I had:

`<script src="assets/lib/tinymce/tinymce.min.js"></script>`

And that worked. However, if I move the include to .angular-cli.json, like so:

```
      "scripts": [
        "../src/assets/lib/tinymce/tinymce.min.js"
      ],
```
I get the following error:

`:4200/themes/modern/theme.js Failed to load resource: the server responded with a status of 404 (Not Found)`

I think this is a bug?

**Comment by fyrkant** [comment]
No this isn't a bug, I think you just have to add all the scripts to the scripts array in .angular-cli.json. But if it was working with the script tag, why change it?

**Comment by rplst8** [comment]
> But if it was working with the script tag, why change it?
Because then it doesn't get rolled into the scripts.bundle.js with webpack.

**Comment by fyrkant** [comment]
You should be able to just import tinymce in your code instead of using the json config thing, so like this:

```ts
import 'tinymce';
import 'tinymce/themes/modern';
// if you use any plugins you have to include them too
```

Although you also have to make sure to load in the skin, maybe easiest by just copying the folder from `node_modules/tinymce/skins` to  `src/assets/skins` and then set the `skin_url` in the editor like this: `<editor [init]="{skin_url: 'assets/skins/lightgray'}"></editor>`

**Comment by fyrkant** [comment]
Closing this as it isn't an issue with the package.
