### ISSUE TITLE
click on emoticons-icon on the toolbar should fire an event

### ISSUE THREAD

**Issue by YusufIpek** [tinymce/tinymce-angular#204]
**I need an event which gets fired when the emoticons-icon on the toolbar is clicked**
(onChange) is only fired when an emoji is selected from the modal, but I need an event, which gets fired when the modal is opened.

Maybe there is already an event, does anybody know?

**Comment by jscasca** [comment]
Hi @YusufIpek 

Since this is the angular wrapper repo we only focus on issues regarding component support in Angular, maybe your query can be addressed properly in the tinymce repo?

What is your particular use case? To my very limited knowledge, the only event triggered by opening the emoticon modal window is `OpenWindow`, in order to find out if the open window is the emoticon window you would need to check the contents of the dialog. Something like:
```
setup: (e) => {
  e.on('OpenWindow', (d) => {
    isEmoticonDialog = (w) => { return w.dialog.getData().pattern !== undefined && w.dialog.getData().results !== undefined};
    if (isEmoticonDialog(d)) {
...
```

**Comment by jscasca** [comment]
@YusufIpek did you manage to workaround your issue?
