### ISSUE TITLE
[inline]="true" is not working / no tinymce visible

### ISSUE THREAD

**Issue by patrickbussmann** [tinymce/tinymce-angular#32]
The "inline" mode, via the `[inline]="true"` configuration option is empty.

**Code:**

    <editor [(ngModel)]="Text" [inline]="true" name="Text"></editor>

**Rendered:**

    <div _ngcontent-c14="">
        <editor _ngcontent-c14="" name="Text" _nghost-c8="" ng-reflect-inline="true" ng-reflect-name="Text" class="ng-untouched ng-pristine ng-valid">
            
            <div id="tiny-react_21502752331535284906777" class="mce-content-body" contenteditable="true" style="position: relative;" spellcheck="false">
                <p><br data-mce-bogus="1"></p>
            </div><input type="hidden" name="tiny-react_21502752331535284906777">
        </editor>
    </div>

But it's empty. 😢 

![2018-08-26 14_13_53](https://user-images.githubusercontent.com/15617021/44628114-525faf80-a93a-11e8-9868-fecf67f37335.png)

Same like in the AngularJS version: https://github.com/angular-ui/ui-tinymce/issues/41

**Comment by fyrkant** [comment]
Is the model correct? Inline editor work without problems in my testing.

**Comment by pbarranis** [comment]
@patrickbussmann try removing the square brackets and changing it to `inline="true"`.  I was just about to file an issue that this Angular wrapper doesn't seem to support using binding on any of the attributes like apiKey and init (AFAIK... I'm still investigating/verifying).  I suspect the code expects the value to be available at the time of the constructor or onInit, when I believe you have to wait for ngAfterInit / OnAfterInit for `@Input()` values to be fully specified.

**Comment by pbarranis** [comment]
I'm sorry, I spoke too soon.  I looked at the code, and the binding should be working just fine for most fields.  However, I can also confirm the putting `inline="true"` will *not* work but putting `[inline]="true"` *does* work just fine.  I would guess that the former doesn't work because it would assign the string "true" to the field (despite the typescript type declaration) whereas the latter would assign it to the boolean `true`.  

(As a side note, forcing someone to use binding on this particular attribute/input is probably overkill; it would be super-great if someone could make it support setting it as a pure attribute.  I think that would be a trivial code change...?)

**Comment by fyrkant** [comment]
What do you mean with a pure attribute?

**Comment by pbarranis** [comment]
@fyrkant sorry, I mean it would be great if `inline="true"` (syntactically like a normal HTML attribute) in addition to what already works, which is `[inline]="true"`.  The former is faster for Angular since it doesn't cause any binding to happen.  

The only difference for the TinyMCE code is that you'd have to detect that the value of `this.inline` is a string set to the value "true".

**Comment by fyrkant** [comment]
@pbarranis I've now changed so you can use the inline attribute like an HTML5 boolean attribute, that is that it will be considered `true` if it is present regardless of it's value, so you can use it like this now `<editor inline></editor>`.

Closing this issue as I never got a response from the creator.
