### ISSUE TITLE
Error: export 'takeUntil' (imported as 'takeUntil') was not found in 'rxjs' in latest version 8.0.0

### ISSUE THREAD

**Issue by Mehadmushtaq** [tinymce/tinymce-angular#388]
i installed the latest available version of **@tinymce/tinymce-angular** which is **8.0.0**, after successful installation when i try to build my project it throws an unexpected error as you can see below:

![image](https://github.com/tinymce/tinymce-angular/assets/64118753/b0648a13-3faf-4b87-9871-6325cf30dc99)

when i just navigate to tinymce-tinymce-angular.mjs i found that **takeUntil** is imported directly from **rxjs** which was changed after rxjs v5 and now we have to import it from "rxjs/operators" instead of "rxjs" that i throwing error. 

here is the image showing tinymce-tinymce-angular.mjs file:
![image](https://github.com/tinymce/tinymce-angular/assets/64118753/73655104-464f-42d6-a72e-e0df8bfe3a4f)

**Comment by danoaky-tiny** [comment]
RxJS has [deprecated the `'rxjs/operators'`](https://rxjs.dev/guide/importing#new-in-rxjs-v720) import since v7.2.0 (3 years ago). 
Although I understand that [Angular 17 still supports using RxJS ^6.5.3](https://angular.io/guide/versions#actively-supported-versions). So at the very least I think we should add RxJS v7.4.0 as a peer dependency to this package.

Personally I'm much less inclined to put back support for deprecated RxJS imports, but if more people have this problem we'll consider a patch for it.

**Comment by danoaky-tiny** [comment]
Closing, as #389 is merged
