### ISSUE TITLE
license_key: 'gpl' currrently not working?

### ISSUE THREAD

**Issue by melino** [tinymce/tinymce-angular#406]
Our  self-hosted TinyMCE 7 works like a charme in our Angular 18 app, but somehow we still get the **console** message

`TinyMCE is running in evaluation mode. Provide a valid license key or add license_key: 'gpl' to the init config ...`

We have tried all possible ways to get rid of it, of corse with `license_key: 'gpl'` within the confic object first, but also with the API key in the HTML, which isn't needed for self-host.
Now we come to the point that we think it could be an issue with the current version of TinyMCE.

Here's a [Stackblitz](https://stackblitz.com/~/github.com/melino/tinymec) with minimal setup.

Does anyone experience the same or knows a fix?

![Image](https://github.com/user-attachments/assets/8586ef83-cd67-4cf5-bed3-0143de9a6a6f)

**Comment by kemister85** [comment]
Hi @melino 👋,

After reviewing your [Stackblitz demo](https://stackblitz.com/~/github.com/melino/tinymec), the issue stems from an incorrect format in your `app.component.html`. To resolve this, update your implementation to match the expected format as outlined in the [Angular Integration Guide](https://www.tiny.cloud/docs/tinymce/latest/angular-ref/#configuring-the-editor). Specifically, the `licenseKey` should be explicitly defined in the `app.component.html` file instead of being inherited from a service.

Correct Example:

`<editor
  [init]="tinyMceConfig"
  initialValue="Start writing here..."
  [inline]="false"
  plugins="lists link"
  toolbar="undo redo | bold italic"
  licenseKey="gpl"
></editor>`

Previously, the integration demo included the `license_key: 'gpl'` property in the service configuration, which caused a warning because it did not align with the expected format.

Additionally, update your `tiny-mce-config.service.ts` to the following:

`import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class TinyMceConfigService {
  config = {
    base_url: '/tinymce',
    suffix: '.min',
    promotion: false,
    branding: false,
  };
}`

This ensures the configuration adheres to the recommended structure. Let me know if you encounter any further issues with your setup.

**Comment by melino** [comment]
Great, solved. - Thank you!

For all that come after me: if it does not work with the first try, delete all your caches.
