### ISSUE TITLE
FormControl.setValue will cause the form.pristine to be false

### ISSUE THREAD

**Issue by hansip** [tinymce/tinymce-angular#80]
Hi, I created a demo to show this at https://stackblitz.com/edit/angular-zbycyn
When you click on the button 'Update Name' (uses the typical _input_ element), the form.pristine stays true. When you click on the button 'Update Description' (uses _editor_ aka tinymce), the form.pristine became false.
They both uses FormControl.setValue (same with using patchValue).
I am expecting both buttons behave the same in regards to keeping the form to be pristine.

**Comment by ansells** [comment]
I think this might be due to the fact that tinymce-angular is calling the onChangeCallback() in response to the 'setcontent' event from the editor. 

I tried to work around this in my code by comparing the "changed" content to see if it was the same value as before, but it also appears that the callback is being made with the raw html value from the editor that includes all the "data-mce-" temporary nodes. It seems like it should be calling editor.getContent() as it does in response to the other edit events.

**Comment by SimonFc** [comment]
@ansells You were right about the source of the issue. As far as I could tell having the callback on setContent was a mistake. Setting the value programmatically with angulars writeValue(or Tiny's setContent, which would be its equivalent) shouldn't invoke that callback. All other cases should already be handled by the callback below that one.

A new version is out now(3.0.1) which contains a fix. Thank you hansip for reporting this issue!

**Comment by hansip** [comment]
Awesome, I'll check out v3.0.1. Thanks for the help @ansells and @SimonFc

**Comment by ansells** [comment]
Glad to hear it. Will pull the latest and dump my own branch. @SimonFc Thanks for the quick turnaround.

**Comment by hansip** [comment]
Hi @SimonFc, I just tried testing it by upgrading to 3.0.1. It seems to still change the 'pristine' state of the form?
https://stackblitz.com/edit/angular-zbycyn-tc9guf

**Comment by SimonFc** [comment]
Seems to be second cause for this. Since the buttons don't have a specified type they'll default to submit inside the form element
```
...
<button type="submit" (click)="updateDescription()">Update Description</button>
```
When the form is [submitted](https://www.tiny.cloud/docs/quick-start/#step3savingcontentwithaformpost) the editor will save its content and create a new undo-level and this, in turn, is what will cause the editor to become !pristine...

So there're two things to do here - either set the button type to `type="button"`, or set the following option on the editor: `[init]="{add_form_submit_trigger: false}"`. Hmm strangely enough the `add_form_submit_trigger` option doesn't seem to be documented at all.

**Comment by hansip** [comment]
Oh great, thanks for that 😄. Yeah I verified it works, thanks again.

**Comment by ansells** [comment]
Just verified fix in my code so now I can toss my personal branch

Thanks for getting the fix out!
