### ISSUE TITLE
Use custom angular components inside rich text

### ISSUE THREAD

**Issue by Liero** [tinymce/tinymce-angular#85]
Hi is the tinymce capable of displaying custom angular components inside rich text?

For example, I want to replace some tokens with angular components, e.g.:

`Hello, @John`, would be replaced by `Hello, <app-username user="John"></app-username>`

**Comment by SimonFc** [comment]
Hi Liero,
Just so that I understand it correctly, you want to have a component managed by Angular appended to the `contenteditable` area of Tiny's iframe? I managed to do it similarly to how [this post](https://stackoverflow.com/a/44193874) on stackoverflow is describing. (This is definitely nothing that's supported by Tiny though so do expect some very odd behavior)

What is it that you're trying to do? Tiny do support [mentions](https://www.tiny.cloud/docs/plugins/mentions/) functionality so that might cover your case.

**Comment by Liero** [comment]
Well, I'm trying to do mentions, hashtags (the same as mentions but starting with #) and one more similar, that I forgot right now :) Is it possible to use mentions plugin also for hashtags simultaneously with mentions?

I would also like to reformat plain text, that contains @mentions and #tags automatically on page load.

**Comment by SimonFc** [comment]
I took a look at the mentions plugin and the trigger-character seems to be hard-coded to "@" so that would unfortunately not be possible.

I see now why you would want to add the Angular component to Tiny :) I advise though, if the existing mentions plugin isn't what you're looking after, is to implement what you need to do as a plugin instead of reaching into "Tiny's domain" with Angular. (Both when it comes to functionality and the UI) Let me know if you got any questions!
