### ISSUE TITLE
<editor> is a too general name for a selector

### ISSUE THREAD

**Issue by swirlsky** [tinymce/tinymce-angular#88]
Have you considered giving a more specific name for the selector used in the template? <tinymce... or something similar would be more appropriate I think.

**Comment by tinydylan** [comment]
This sounds like a reasonable enhancement. The only concern is backwards compatibility, so it'd need to be in a major version bump.

**Comment by danoaky-tiny** [comment]
Since this is such an old ticket I'm going to close this as not planned for now. If anybody is still interested in this, feel free to open a new issue.

Otherwise in my opinion, most of the other integrations also have their default selector or export name as Editor/editor. So as it is right now it keeps consistency.
As well as this, you would almost certainly be wrapping our component in your own, with its own name/selector that you can choose.
