### ISSUE TITLE
Can't have multiple editor on single page

### ISSUE THREAD

**Issue by njanice** [tinymce/tinymce-angular#92]
I already set up the tinymce and loading tinymce on my own instead of using apiKey and use formControlName instead of ngModel.

It works if I only have one editor in one page. However, if I have multiple then only the first editor become the rich text editor and the other becomes blank

I've tried all solutions I could find but still not working.

**Comment by SimonFc** [comment]
Hi @njanice, in what way are you setting up multiple editors? Do you have an example of your setup which showcases this issue?

**Comment by gentoo90** [comment]
I stepped on this too. It turned out that if multiple editors have the same `id`, then only one of them will work properly. Which makes perfect sense, but it would be nice to have some error or warning in the console about this kind of situation. Right now it's just silently broken.

**Comment by tinydylan** [comment]
I can reproduce this issue in a code sandbox: https://codesandbox.io/s/tinymceangular-forked-drojm?file=/src/app/app.component.html

I agree it would be better if we raised an error when this happened. Since there's a workaround, I'll remove the "status:escalated" tag.

**Comment by Ahd-Kabeer-Hadi** [comment]
I'm having the same issue here as in @tinydylan 's sandbox but in my case, it's in the first one, and I'm using tinyMCE 6 with angular js, and have different ids for each instance, any idea why it is happening? there's no error or warning in the console 

I'm sharing here how my configurations are
` scope.id = Math.random().toString(36).replace(/[^a-z]+/g, '');
tinymce.init({
                    selector: '#'+scope.id,
})
`
` <div id="{{id}}"></div>`

I'm not using `inline` here because when it is added as `true` neither of them loads even with textarea
it'll be helpful if there's an alert or something that helps to find where it went wrong
